syntax = "proto3";

package whoismudry.proto;

message Vec2 {
    float x = 1;
    float y = 2;
}

enum Direction {
    DIRECTION_UNSPECIFIED = 0;
    DIRECTION_UP = 1;
    DIRECTION_DOWN = 2;
    DIRECTION_LEFT = 3;
    DIRECTION_RIGHT = 4;
}

message PlayerState {
    string id = 1;
    Vec2 position = 2;
    Direction facing = 3;
    bool is_moving = 4;
    string username = 5;
}

message JoinGame {
    string username = 1;
}

message SendInput {
    float dx = 1;
    float dy = 2;
}

message Disconnect {
}

message Welcome{
    string player_id = 1;
    repeated TaskState tasks = 2;
}

message PlayerLeft {
    string player_id = 1;
}

message WorldSnapshot{
    repeated PlayerState players = 1;
}
message TaskState {
    string id = 1;
    Vec2 position = 2;
    string task_type = 3;
}