syntax = "proto3";

package whoismudry.proto;

message Vec2 {
    float x = 1;
    float y = 2;
}

enum Direction {
    DIRECTION_UNSPECIFIED = 0;
    DIRECTION_UP = 1;
    DIRECTION_DOWN = 2;
    DIRECTION_LEFT = 3;
    DIRECTION_RIGHT = 4;
}

message PlayerState {
    string id = 1;
    Vec2 position = 2;
    Direction facing = 3;
    bool is_moving = 4;
    string username = 5;
    bool is_dead = 6;
    int64 last_kill_time = 7;
}

message JoinGame {
    string username = 1;
}

message SendInput {
    float dx = 1;
    float dy = 2;
}

message Disconnect {
}

message Welcome{
    string player_id = 1;
    repeated TaskState tasks = 2;
}

message PlayerLeft {
    string player_id = 1;
}

message WorldSnapshot{
    repeated PlayerState players = 1;
    GamePhase phase = 2;
}

message TaskState {
    string id = 1;
    Vec2 position = 2;
    TaskType task_type = 3;
}

enum TaskType {
    TASK_TYPE_UNSPECIFIED = 0;
    TASK_TYPE_ADMIN_CARD = 1;
}

enum GamePhaseType {
    GAME_PHASE_TYPE_UNSPECIFIED = 0;
    GAME_PHASE_TYPE_PLAYING = 1;
    GAME_PHASE_TYPE_DISCUSSION = 2;
    GAME_PHASE_TYPE_VOTING = 3;
    GAME_PHASE_TYPE_LOBBY = 4;
    GAME_PHASE_TYPE_GAME_OVER = 5;
}

message Vote {
    string voter_id = 1;
    string target_id = 2;
}

message GamePhase {
    GamePhaseType phase_type = 1;
    float remaining_time = 2;
    repeated Vote votes = 3;
}

message CallMeeting {
}

message SubmitVote {
    string target_id = 1;
}

enum RoleType {
    ROLE_TYPE_UNSPECIFIED = 0;
    ROLE_TYPE_STUDENTS = 1;
    ROLE_TYPE_MUDRY = 2;
}

message RoleAssignment {
    RoleType role = 1;
}

message KillPlayer {
    string target_id = 1;
}